trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

variables:
  NAME: pyzo
  PY_ARCH: x64
  PY_VERSION: 3.6

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
        SDIST: 1
        LINT: 1
      MacOS:
        vmImage: macOS-10.14
        MACOSX_DEPLOYMENT_TARGET: '10.13'
      Windows:
        vmImage: vs2017-win2016
      Windows-32:
        vmImage: vs2017-win2016
        PY_ARCH: x86
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UsePythonVersion@0
    displayName: Select Python
    inputs:
      versionSpec: $(PY_VERSION)
      architecture: $(PY_ARCH)
  - task: Bash@3
    displayName: Install development requirements
    inputs:
      targetType: inline
      script: |
        set -ex
        python -m pip install -U pip
        pip install -U pyqt5
        pip install -U pytest black flake8 pyinstaller
  - task: Bash@3
    displayName: Install inno setup (on Windows)
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows'))
    inputs:
      targetType: inline
      script: |
        set -ex
        # Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install innosetup
  - task: Bash@3
    displayName: Lint (black & flake8)
    condition: and(succeeded(), eq(variables['LINT'], '1'))
    inputs:
      targetType: inline
      script: |
        set -ex
        black --check .
        flake8 .
  - task: Bash@3
    displayName: Install sdist
    inputs:
      targetType: inline
      script: |
        set -ex
        python setup.py sdist
        pip install $(echo "$(Build.SourcesDirectory)" | sed -e 's/\\/\//g')/dist/*.tar.gz
  - task: Bash@3
    displayName: Test
    inputs:
      targetType: inline
      script: |
        set -ex
        pytest --junit-xml=results.xml tests || true

        # Fail the task if results.xml was not created
        if [[ ! -f results.xml ]]
        then
          echo "##vso[task.logissue type=error]No test results were found"
          exit 1
        fi
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: results.xml
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: Test $(vmImage)
  - task: Bash@3
    displayName: Freeze
    inputs:
      targetType: inline
      script: |
        python freeze/freezeScript.py
        rm -rf ./frozen/pyzo
        rm -rf ./frozen/pyzo.app
  - task: PublishBuildArtifacts@1
    displayName: Publish distributions
    inputs:
      pathtoPublish: frozen
      artifactName: frozen

- job: Release
  dependsOn: Build
  # condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: Bash@3
    displayName: git tag == git branch
    inputs:
      targetType: inline
      script: |
        set -ex
        IS_TAG_BUILD=$(expr $(git describe --tags) == $(Build.SourceBranchName)) || true
        echo "##vso[task.setvariable variable=IS_TAG_BUILD]$IS_TAG_BUILD"
        if [[ $IS_TAG_BUILD != 1 ]]; then
          echo This build was not triggered by a tag, aborting release
        fi
  - task: UsePythonVersion@0
    displayName: Select Python
    # condition: and(succeeded(), eq(variables['IS_TAG_BUILD'], '1'))
    inputs:
      versionSpec: $(PY_VERSION)
  - task: DownloadBuildArtifacts@0
    displayName: Download dist
    # condition: and(succeeded(), eq(variables['IS_TAG_BUILD'], '1'))
    inputs:
      artifactName: frozen
      downloadPath: .
  - task: GithubRelease@1
    displayName: GitHub Release
    # condition: and(succeeded(), eq(variables['IS_TAG_BUILD'], '1'))
    inputs:
      gitHubConnection: github.com_almarklein
      repositoryName: 'pyzo/pyzo'
      assets: |
        frozen/*.zip
        frozen/*.tar.gz
        frozen/*.exe
        frozen/*.msi
        frozen/*.dmg
      isDraft: true
      addChangeLog: false
      assetUploadMode: replace
