name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-build:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dev dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U black flake8 flake8-black
    - name: Flake8
      run: |
          flake8 .

  test-builds:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python versions
          - name: Test Linux py36
            os: ubuntu-latest
            pyversion: '3.6'
            qtlib: pyside6
          - name: Test Linux py37
            os: ubuntu-latest
            pyversion: '3.7'
            qtlib: pyside6
          - name: Test Linux py38
            os: ubuntu-latest
            pyversion: '3.8'
            qtlib: pyside6
          - name: Test Linux py39
            os: ubuntu-latest
            pyversion: '3.9'
            qtlib: pyside6
          # OS's
          - name: Test Windows py310
            os: windows-latest
            pyversion: '3.10'
            qtlib: pyside6
          - name: Test MacOS py310
            os: macos-latest
            pyversion: '3.10'
            qtlib: pyside6
          # Qt libs
          - name: Test Linux py310 PyQt5
            os: ubuntu-latest
            pyversion: '3.10'
            qtlib: pyqt5
          - name: Test Linux py310 PyQt6
            os: ubuntu-latest
            pyversion: '3.10'
            qtlib: pyqt6
          - name: Test Linux py310 PySide2
            os: ubuntu-latest
            pyversion: '3.10'
            qtlib: pyside2
          - name: Test Linux py310 PySide6
            os: ubuntu-latest
            pyversion: '3.10'
            qtlib: pyside6
    steps:
    - uses: actions/checkout@v2
    - name: Setup os
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libegl1-mesa
    - name: Set up Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -U ${{ matrix.qtlib }}
    - name: Install in development mode
      run: |
          pip install -e .
    - name: Test on repo
      run: |
          pytest -v tests
    - name: Run Pyzo
      run: |
          python pyzo --test
